### ISSUE TITLE
Patch size inconsist

### ISSUE THREAD

**Issue by Tmyann** [tonyjo/edlsm_pytorch#3]
Hi, when I run the code an error occurred which says the size of tensors does not match. And I find sometimes the patch generated by the data loader is of size (3, 34, 37). How to solve this?

**Comment by tonyjo** [comment]
This was specifically written for the http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo dataset. Are you running the code on this dataset?

**Comment by Tmyann** [comment]
Yes, I am trying to train with the Kitti 2015 dataset.

**Comment by Tmyann** [comment]
Here is the initial error log:
>Traceback (most recent call last):
  File "train.py", line 45, in <module>
    tf.app.run()
  File "/home/yann/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 41, in main
    edlsm.train(FLAGS)
  File "/home/yann/Documents/edlsm_pytorch/src/edlsm_learner.py", line 69, in train
    left_batch, right_batch = next(train_gen)
  File "/home/yann/Documents/edlsm_pytorch/src/data_Loader.py", line 163, in gen_data_batch
    Here is the initial error log:
>Traceback (most recent call last):
  File "train.py", line 45, in <module>
    tf.app.run()
  File "/home/yann/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 41, in main
    edlsm.train(FLAGS)
  File "/home/yann/Documents/edlsm_pytorch/src/edlsm_learner.py", line 69, in train
    left_batch, right_batch = next(train_gen)
  File "/home/yann/Documents/edlsm_pytorch/src/data_Loader.py", line 163, in gen_data_batch
    image_l_batch = torch.FloatTensor(image_l_batch)
ValueError: only one element tensors can be converted to Python scalars

I think the problem is that torch.FloatTensor cannot convert a list of tensors to tensors.
So I change this to
`image_l_batch = torch.stack(image_l_batch)`
and this works. But another bug arises as I mentioned in this issue:

>Traceback (most recent call last):
  File "train.py", line 45, in <module>
    tf.app.run()
  File "/home/yann/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 41, in main
    edlsm.train(FLAGS)
  File "/home/yann/Documents/edlsm_pytorch/src/edlsm_learner.py", line 69, in train
    left_batch, right_batch = next(train_gen)
  File "/home/yann/Documents/edlsm_pytorch/src/data_Loader.py", line 165, in gen_data_batch
    image_l_batch = torch.stack(image_l_batch)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 37 and 35 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMath.c:3586

**Comment by tonyjo** [comment]
This code was written a while ago, I am sure about this. 
1. Make sure you are using the torch version as in the requirements.
2. For debugging I would test the `data_Loader.py` alone and run it to print the shapes to make sure the sizes are same, if there is a mismatch, I would simply remove that particular dataset item and use the rest or add some padding to match the size.

**Comment by Tmyann** [comment]
OK, thanks a lot for your time!
